[package]
name = "bmvm-common"
version = "0.1.0"
edition = "2024"

[features]
std = ["anyhow", "memchr"]

[dependencies]
bitflags = "2.9.1"
sealed = "0.6.0"
anyhow = { version = "1.0.98", optional = true }
memchr = { version = "2.7.4", optional = true }
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
x86_64 = "0.15.2"
spin = { version = "0.10.0", default-features = false, features = ["once"] }