[workspace]
resolver = "3"
members = [
    # Core Components
    "bmvm_guest",
    "bmvm_common",
    "bmvm_macros",
    "bmvm_host",
    # Examples
    "examples/guest",
    "examples/host",
    # Debug Tooling
    "tooling/printlayout",
    "tooling/vmi-inspect",
    # Benchmarking: Setup Noop Guest
    "bench/setup-noop/bmvm_guest_noop",
    "bench/setup-noop/bmvm_host_setup",
    "bench/setup-noop/wasmtime_setup_noop",
    # Benchmarking: Linking performance
    "bench/setup-linking/bmvm_guest_expose",
    "bench/setup-linking/bmvm_host_expose",
]
