[workspace]
resolver = "3"
members = [
    "bmvm_guest",
    "bmvm_common",
    "bmvm_host",
    "examples/guest",
    "bmvm_macros",
    "examples/host",
    "examples/host-expand",
    "examples/longmode",
    "tooling/printlayout",
    "tooling/vmi-inspect",
]
