[workspace]
resolver = "3"
members = [
    # Core Components
    "bmvm_guest",
    "bmvm_common",
    "bmvm_macros",
    "bmvm_host",
    # Examples
    "examples/guest",
    "examples/host",
    # Debug Tooling
    "tooling/printlayout",
    "tooling/vmi-inspect",
    # Benchmark Guests
    "bench/bmvm_guest_noop",
]
