[workspace]
resolver = "3"
members = [
    "bmvm_guest",
    "bmvm_common",
    "bmvm_macros",
    "bmvm_host",

    "examples/guest",
    "examples/host",

    "tooling/printlayout",
    "tooling/vmi-inspect",

    "bench/setup-linking/bmvm_guest_expose",
    "bench/setup-linking/bmvm_startup_setup_expose",
]
