cargo-features = ["per-package-target"]

[package]
name = "wasm-echo"
version = "0.1.0"
edition = "2024"
forced-target = "wasm32-unknown-unknown"

[dependencies]
talc = "4.4.3"
spin = "0.10.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
opt-level = 3
