[package]
name = "guest"
version = "0.1.0"
edition = "2024"

[dependencies]
bmvm-guest = {path = "../../bmvm_guest", features = ["vmi-no-debug", "setup"]}

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = false
