[package]
name = "kvm_guest_sample"
version = "0.1.0"
edition = "2024"

[dependencies]
bmvm-guest = {path = "../../bmvm_guest" }
bmvm-common = {path = "../../bmvm_common", default-features = false}

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
