cargo-features = ["per-package-target"]

[package]
name = "bmvm-echo"
version = "0.1.0"
edition = "2024"
forced-target = "x86_64-unknown-none"

[dependencies]
bmvm-guest = {path="../../bmvm_guest"}

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
opt-level = 3
