[package]
name = "printlayout"
version = "0.1.0"
edition = "2024"

[dependencies]
bmvm-common = { path= "../../bmvm_common", features = ["vmi-consume"]}
clap = { version = "4.5.40", features = ["derive", "env"] }
anyhow = "1.0.98"
tabled = "0.20.0"