[package]
name = "host"
version = "0.1.0"
edition = "2024"

[dependencies]
bmvm-host = { path = "../../bmvm_host", features = ["benchmarks"]}
anyhow = "1.0.98"
env_logger = "0.11.8"
log = "0.4.27"
clap = { version = "4.5.40", features = ["derive", "env"] }
