[package]
name = "ctx"
version = "0.1.0"
edition = "2024"

[dependencies]
kvm-ioctls = "0.24.0"
kvm-bindings = "0.14.0"
libc = "0.2.175"

[[bench]]
name = "switch"
harness = false

[dev-dependencies]
criterion = { version = "0.7.0", features = ["html_reports"] }