[package]
name = "kvm_guest_sample"
version = "0.1.0"
edition = "2024"

[dependencies]
kvm_guest = {path = "../kvm_guest"}

[profile.dev]
panic = "abort"

[profile.release]
lto = true
panic = "abort"
