cargo-features = ["per-package-target"]

[package]
name = "bmvm-guest-noop"
version = "0.1.0"
edition = "2024"
forced-target = "x86_64-unknown-none"

[dependencies]
bmvm-guest = {path="../../../bmvm_guest", features = ["setup"]}

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"


